//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kres
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRESLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KRESLER()
        {
            this.OGRENCI_BİLGİ = new HashSet<OGRENCI_BİLGİ>();
            this.PERSONELs = new HashSet<PERSONEL>();
            this.SINIFs = new HashSet<SINIF>();
        }
    
        public int Kres_Id { get; set; }
        public string Kres_Ad { get; set; }
        public string Kres_Adres { get; set; }
        public int Kres_Kontenjan { get; set; }
        public string Kres_İletisim { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRENCI_BİLGİ> OGRENCI_BİLGİ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONEL> PERSONELs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINIF> SINIFs { get; set; }
    }
}
