//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kres
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENCI_BİLGİ
    {
        public int Ogrenci_Id { get; set; }
        public string Ogrenci_Ad { get; set; }
        public string Ogrenci_Soyad { get; set; }
        public string Ogrenci_Yas { get; set; }
        public string Ogrenci_Cinsiyet { get; set; }
        public int Ogrenci_Sınıf_Id { get; set; }
        public string Veli_Adı { get; set; }
        public string Veli_Iletisim { get; set; }
        public string Orenci_Adres { get; set; }
        public int Kres_Id { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual KRESLER KRESLER { get; set; }
        public virtual SINIF SINIF { get; set; }
    }
}
