//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kres
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONEL()
        {
            this.SINIFs = new HashSet<SINIF>();
        }
    
        public int Personel_Id { get; set; }
        public string Personel_Ad { get; set; }
        public string Personel_Soyad { get; set; }
        public string Personel_Iletisim { get; set; }
        public string Personel_eMail { get; set; }
        public string Personel_Adres { get; set; }
        public string Personel_Yetki { get; set; }
        public int Kres_Id { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual KRESLER KRESLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINIF> SINIFs { get; set; }
    }
}
