//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kres
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINIF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINIF()
        {
            this.OGRENCI_BİLGİ = new HashSet<OGRENCI_BİLGİ>();
        }
    
        public int Sınıf_Id { get; set; }
        public string Sınıf_Ad { get; set; }
        public int Sınıf_Kontenjan { get; set; }
        public int Personel_Id { get; set; }
        public int Kres_Id { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual KRESLER KRESLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRENCI_BİLGİ> OGRENCI_BİLGİ { get; set; }
        public virtual PERSONEL PERSONEL { get; set; }
    }
}
