//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kres
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKI
    {
        public int Yetki_Id { get; set; }
        public string Yetki_turu { get; set; }
        public string Yetkili_ad { get; set; }
        public string Yetkili_Iletisim { get; set; }
        public string Yetkili_Adres { get; set; }
        public string Yetkili_eMail { get; set; }
        public string Yetkili_Sifre { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
